"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "fr" | "en" | "ar";

type Dictionary = {
    [key: string]: string;
};

const translations: Record<Language, Dictionary> = {
    fr: {
        "queue.title": "File d'attente",
        "queue.empty": "Aucun patient en attente",
        "current.title": "Patient actuel",
        "current.none": "Aucun patient actif",
        "current.start": "Démarrer la file",
        "current.helper": "Le premier patient sera appelé",
        "action.next": "Suivant",
        "action.finish": "Terminer",
        "action.cancel": "Annuler",
        "action.urgent": "Urgent",
        "action.delay": "Retarder",
        "header.status.active": "File active",
        "header.status.stopped": "File arrêtée",
        "settings.title": "Paramètres",
        "settings.questions": "Questions pour les patients",
        "logout": "Se déconnecter",
        "nav.home": "Accueil",
        "nav.features": "Fonctionnalités",
        "nav.howItWorks": "Comment ça marche",
        "nav.pricing": "Tarifs",
        "nav.contact": "Contact",
        "nav.demo": "Démo Médecin",
        "hero.headline": "Gérez votre file d'attente.",
        "hero.subheadline": "Simplement.",
        "hero.subtitle": "Optimisez le flux des patients, réduisez l'attente et libérez votre personnel avec ClinicFlow.",
        "hero.cta": "Commencer maintenant",
        "hero.login": "Connexion Médecin",
        "cta.title": "Prêt à moderniser votre clinique ?",
        "cta.button": "Commencer l'essai gratuit",
        "footer.rights": "Tous droits réservés.",
        "footer.privacy": "Politique de confidentialité",
        "admin.sidebar.clinics": "Cliniques & Abonnements",
        "admin.sidebar.support": "Tickets de Support",
        "admin.sidebar.overview": "Vue d'ensemble",
        "admin.clinics.title": "Gestion des Cliniques",
        "admin.clinics.subtitle": "Gérez les cliniques et les abonnements.",
        "admin.clinics.search": "Rechercher par nom, email ou slug...",
        "admin.clinics.table.clinic": "Clinique",
        "admin.clinics.table.subscription": "Abonnement",
        "admin.clinics.table.patients": "Patients",
        "admin.signout": "Déconnexion",
        // Settings FR
        "admin.settings.title": "Paramètres Généraux",
        "admin.settings.app": "Paramètres de l'application",
        "admin.settings.app.name": "Nom de l'application",
        "admin.settings.app.logo": "Logo",
        "admin.settings.app.change": "Modifier",
        "admin.settings.app.lang": "Langues",
        "admin.settings.app.lang.desc": "Arabe, Anglais, Français",
        "admin.settings.subs": "Paramètres d'abonnement par défaut",
        "admin.settings.subs.trial": "Durée de l'essai (jours)",
        "admin.settings.subs.plan": "Plan par défaut",
        "admin.settings.btn.save": "Sauvegarder",
        "admin.settings.btn.cancel": "Annuler",
        // Admin FR
        "admin.sidebar.dashboard": "Tableau de bord",
        "admin.sidebar.users": "Utilisateurs",
        "admin.sidebar.subscriptions": "Abonnements",
        "admin.sidebar.plans": "Plans",
        "admin.sidebar.periods": "Périodes",
        "admin.sidebar.features": "Fonctionnalités",
        "admin.sidebar.settings": "Paramètres",
        "admin.sidebar.logs": "Journaux",
        "admin.header.superadmin": "Super Admin",
        "admin.dashboard.title": "Vue d'ensemble",
        "admin.stats.users": "Utilisateurs Totaux",
        "admin.stats.activeSubs": "Abonnements Actifs",
        "admin.stats.revenue": "Revenu Mensuel",
        "admin.stats.trials": "Essais Actifs",
        "admin.users.title": "Gestion des Utilisateurs",
        "admin.users.filter.plan": "Filtrer par Plan",
        "admin.users.filter.status": "Filtrer par Statut",
        "admin.users.search": "Rechercher",
        "admin.table.user": "Utilisateur",
        "admin.table.plan": "Plan",
        "admin.table.status": "Statut",
        "admin.table.date": "Date",
        "admin.table.actions": "Actions",
        // Features FR
        "admin.features.title": "Gestion des Fonctionnalités",
        "admin.features.subtitle": "Activez ou désactivez les fonctionnalités par plan ou par utilisateur.",
        "admin.features.table.name": "Nom",
        "admin.features.table.desc": "Description",
        "admin.features.table.status": "Statut Global",
        "admin.features.table.plans": "Plans Activés",
        "admin.features.table.override": "Exceptions",
        "admin.features.btn.manage": "Gérer Exceptions",
        "admin.feature.qrcode": "QR Code",
        "admin.feature.qrcode.desc": "Permettre aux patients de scanner pour prendre un ticket",
        "admin.feature.appointments": "Rendez-vous",
        "admin.feature.appointments.desc": "Système de prise de rendez-vous en ligne",
        "admin.feature.sms": "Rappels SMS",
        "admin.feature.sms.desc": "Envoyer des rappels automatiques aux patients",
        "admin.feature.multi": "Multi-praticiens",
        "admin.feature.multi.desc": "Gérer plusieurs médecins dans une clinique",
        "admin.feature.analytics": "Analytiques",
        "admin.feature.analytics.desc": "Rapports détaillés et statistiques",
        "admin.feature.branding": "Marque Blanche",
        "admin.feature.branding.desc": "Supprimer le logo ClinicFlow",
        // Plans FR
        "admin.plans.title": "Gestion des Plans",
        "admin.plans.btn.create": "Créer un Plan",
        "admin.plans.monthly": "Prix Mensuel",
        "admin.plans.yearly": "Prix Annuel",
        "admin.plans.features": "Fonctionnalités",
        "admin.plans.limits": "Limites",
        "admin.plans.limit.users": "Utilisateurs",
        "admin.plans.limit.clinics": "Cliniques",
        "admin.plans.limit.sms": "SMS",
        "admin.plans.btn.edit": "Modifier",
        "admin.plans.btn.disable": "Désactiver",

        // Pricing FR (v3)
        "pricing.v3.title": "Abonnement",
        "pricing.v3.subtitle": "Gérez votre plan et votre facturation",
        "pricing.v3.compare": "Comparez les plans",
        "pricing.v3.save2months": "Économisez 2 mois",
        "pricing.v3.monthly": "Mensuel",
        "pricing.v3.yearly": "Annuel",
        "pricing.v3.trial.title": "Trial",
        "pricing.v3.trial.price": "0 DH",
        "pricing.v3.trial.btn": "Activer Trial",
        "pricing.v3.pro.title": "Pro",
        "pricing.v3.pro.price": "199 DH / mois",
        "pricing.v3.pro.priceYearly": "1990 DH / an",
        "pricing.v3.pro.badge": "RECOMMANDÉ",
        "pricing.v3.pro.btn": "Choisir Pro",
        "pricing.v3.prem.title": "Premium",
        "pricing.v3.prem.btn": "Bientôt",
        "pricing.v3.faq.title": "FAQ",
        "pricing.v3.secure": "Paiement sécurisé",
        "pricing.v3.support": "Support réactif",
        // Shared Features (v3) - Specific text updates
        "pricing.feat.queue": "Gestion de la file d'attente",
        "pricing.feat.qr": "QR Code pour les patients",
        "pricing.feat.dashboard": "Tableau de bord médecin",
        "pricing.feat.multi": "Multi-praticiens",
        "pricing.feat.sms": "SMS avancés",
        "pricing.feat.stats": "Statistiques avancées",
        "pricing.feat.custom": "Personnalisation complète",
        "pricing.v3.subtitle.badge": "SIMPLE & TRANSPARENT",
        "pricing.feat.support24": "Support 24/7",
        // Specific FAQ
        "pricing.faq.free.q": "L'essai est-il gratuit ?",
        "pricing.faq.free.a": "Oui, vous pouvez tester ClinicFlow gratuitement sans carte bancaire.",
        "pricing.faq.change.q": "Puis-je changer de plan ?",
        "pricing.faq.change.a": "Oui, vous pouvez passer du plan Trial au plan Pro à tout moment.",
        // How It Works FR
        "how.title": "Comment fonctionne ClinicFlow?",
        "how.subtitle": "Une solution simple pour organiser la file d'attente des patients dans votre cabinet.",
        "how.btn.free": "Essai gratuit",
        "how.step1.title": "1. Le médecin crée son compte",
        "how.step1.desc": "Le médecin s'inscrit en quelques minutes et configure les informations de son cabinet.",
        "how.step2.title": "2. Les patients prennent un ticket",
        "how.step2.desc": "Les patients prennent leur tour directement au cabinet ou via un QR Code, sans application.",
        "how.step3.title": "3. Le médecin appelle le patient",
        "how.step3.desc": "Depuis le tableau de bord, le médecin appelle le patient suivant en un clic.",
        "how.step4.title": "4. Moins d'attente, plus de confort",
        "how.step4.desc": "Les patients sont informés en temps réel, l'attente est réduite et l'organisation améliorée.",
        "how.why.title": "Pourquoi utiliser ClinicFlow?",
        "how.why.1": "Réduction du temps d'attente",
        "how.why.2": "Organisation fluide du cabinet",
        "how.why.3": "Meilleure expérience patient",
        "how.why.4": "Simple et rapide à utiliser",
        "how.why.5": "Fonctionne sur mobile et ordinateur",
        "how.target.title": "ClinicFlow est fait pour",
        "how.target.1": "Cabinets médicaux",
        "how.target.2": "Médecins généralistes",
        "how.target.3": "Dentistes",
        "how.target.4": "Cliniques privées",
        "how.target.5": "Laboratoires",
        "how.faq.title": "Questions fréquentes",
        "faq.q1": "L'essai est-il gratuit?",
        "faq.a1": "Oui, vous avez 14 jours d'essai gratuit complet, sans carte bancaire requise.",
        "faq.q2": "Les patients ont-ils besoin d'une application?",
        "faq.a2": "Non, aucune application n'est nécessaire. Ils scannent juste un QR Code ou prennent un ticket papier.",
        "faq.q3": "ClinicFlow fonctionne-t-il sans internet?",
        "faq.a3": "ClinicFlow est une solution cloud et nécessite une connexion internet pour synchroniser la file d'attente.",
        "faq.q4": "Puis-je l'utiliser dans une petite clinique?",
        "faq.a4": "Absolument. ClinicFlow est conçu pour s'adapter aux cabinets de toutes tailles, du médecin seul aux grandes cliniques.",
        "how.cta.title": "Simplifiez la gestion de votre cabinet dès aujourd'hui",
        "how.cta.btn": "Commencer gratuitement",
        // Contact FR
        "contact.title": "Contact",
        "contact.subtitle": "Besoin d'aide ou d'une démo ? Contactez-nous et on vous répond rapidement.",
        "contact.tab.demo": "Demander une démo",
        "contact.tab.msg": "Envoyer un message",
        "contact.form.name": "Nom et prénom",
        "contact.form.email": "Email",
        "contact.form.phone": "Téléphone (optionnel)",
        "contact.form.type": "Type de demande",
        "contact.form.type.support": "Support",
        "contact.form.type.sales": "Commercial",
        "contact.form.type.other": "Autre",
        "contact.form.msg": "Message",
        "contact.form.privacy": "J'accepte la politique de confidentialité",
        "contact.form.send": "Envoyer",
        "contact.info.support": "Support",
        "contact.info.whatsapp": "WhatsApp",
        "contact.info.address": "Adresse",
        "contact.info.reply": "Réponse sous 24h",
        "contact.info.avail": "Disponible 9h-18h",
        "contact.demo.title": "Démo Médecin",
        "contact.demo.desc": "On vous montre ClinicFlow en 10 minutes.",
        "contact.demo.clinic": "Nom du cabinet",
        "contact.demo.city": "Ville",
        "contact.demo.slot": "Créneau préféré",
        "contact.demo.book": "Réserver",
        "contact.cta.title": "Simplifiez la gestion de votre cabinet dès aujourd'hui",
        "contact.cta.btn": "Commencer l'essai gratuit",
    },
    en: {
        "queue.title": "Waiting Queue",
        "queue.empty": "No patients waiting",
        "current.title": "Current Patient",
        "current.none": "No active patient",
        "current.start": "Start Queue",
        "current.helper": "The first patient will be called",
        "action.next": "Call Next",
        "action.finish": "Finish",
        "action.cancel": "Cancel",
        "action.urgent": "Urgent",
        "action.delay": "Delay",
        "header.status.active": "Queue Active",
        "header.status.stopped": "Queue Stopped",
        "settings.title": "Settings",
        "settings.questions": "Patient Questions",
        "logout": "Logout",
        "nav.home": "Home",
        "nav.features": "Features",
        "nav.howItWorks": "How it works",
        "nav.pricing": "Pricing",
        "nav.contact": "Contact",
        "nav.demo": "Doctor Demo",
        "hero.headline": "Manage your queue.",
        "hero.subheadline": "Simply.",
        "hero.subtitle": "Optimize patient flow, reduce waiting times, and free up your staff with ClinicFlow.",
        "hero.cta": "Start Now",
        "hero.login": "Doctor Login",
        "cta.title": "Ready to upgrade your clinic?",
        "cta.button": "Start Free Trial",
        "footer.rights": "All rights reserved.",
        "footer.privacy": "Privacy Policy",
        "admin.sidebar.clinics": "Clinics & Subs",
        "admin.sidebar.support": "Support Tickets",
        "admin.sidebar.overview": "Overview",
        "admin.clinics.title": "Clinics Management",
        "admin.clinics.subtitle": "Manage clinics and subscriptions.",
        "admin.clinics.search": "Search by name, email, or slug...",
        "admin.clinics.table.clinic": "Clinic Name",
        "admin.clinics.table.subscription": "Subscription",
        "admin.clinics.table.patients": "Patients",
        "admin.signout": "Sign Out",
        // Settings EN
        "admin.settings.title": "General Settings",
        "admin.settings.app": "Application Settings",
        "admin.settings.app.name": "Application Name",
        "admin.settings.app.logo": "Logo",
        "admin.settings.app.change": "Change",
        "admin.settings.app.lang": "Languages",
        "admin.settings.app.lang.desc": "Arabic, English, French",
        "admin.settings.subs": "Default Subscription Settings",
        "admin.settings.subs.trial": "Default Trial Duration (Days)",
        "admin.settings.subs.plan": "Default Plan",
        "admin.settings.btn.save": "Save Changes",
        "admin.settings.btn.cancel": "Cancel",
        // Admin EN
        "admin.sidebar.dashboard": "Dashboard",
        "admin.sidebar.users": "Users",
        "admin.sidebar.subscriptions": "Subscriptions",
        "admin.sidebar.plans": "Plans",
        "admin.sidebar.periods": "Periods",
        "admin.sidebar.features": "Features",
        "admin.sidebar.settings": "Settings",
        "admin.sidebar.logs": "Logs",
        "admin.header.superadmin": "Super Admin",
        "admin.dashboard.title": "Dashboard Overview",
        "admin.stats.users": "Total Users",
        "admin.stats.activeSubs": "Active Subscriptions",
        "admin.stats.revenue": "Monthly Revenue",
        "admin.stats.trials": "Active Trials",
        "admin.users.title": "Users Management",
        "admin.users.filter.plan": "Filter by Plan",
        "admin.users.filter.status": "Filter by Status",
        "admin.users.search": "Search Users",
        "admin.table.user": "User",
        "admin.table.plan": "Plan",
        "admin.table.status": "Status",
        "admin.table.date": "Date",
        "admin.table.actions": "Actions",
        // Features EN
        "admin.features.title": "Features Management",
        "admin.features.subtitle": "Enable or disable features per plan or override for specific users.",
        "admin.features.table.name": "Feature Name",
        "admin.features.table.desc": "Description",
        "admin.features.table.status": "Global Status",
        "admin.features.table.plans": "Enabled Plans",
        "admin.features.table.override": "User Overrides",
        "admin.features.btn.manage": "Manage Overrides",
        "admin.feature.qrcode": "QR Code",
        "admin.feature.qrcode.desc": "Allow patients to scan code for tickets",
        "admin.feature.appointments": "Appointments",
        "admin.feature.appointments.desc": "Online appointment booking system",
        "admin.feature.sms": "SMS Reminders",
        "admin.feature.sms.desc": "Send automated reminders to patients",
        "admin.feature.multi": "Multi-practitioners",
        "admin.feature.multi.desc": "Manage multiple doctors in one clinic",
        "admin.feature.analytics": "Analytics",
        "admin.feature.analytics.desc": "Detailed reports and statistics",
        "admin.feature.branding": "Custom Branding",
        "admin.feature.branding.desc": "Remove ClinicFlow logo and use custom one",
        // Plans EN
        "admin.plans.title": "Plans Management",
        "admin.plans.btn.create": "Create New Plan",
        "admin.plans.monthly": "Monthly Price",
        "admin.plans.yearly": "Yearly Price",
        "admin.plans.features": "Features",
        "admin.plans.limits": "Limits",
        "admin.plans.limit.users": "Users",
        "admin.plans.limit.clinics": "Clinics",
        "admin.plans.limit.sms": "SMS",
        "admin.plans.btn.edit": "Edit Plan",
        "admin.plans.btn.disable": "Disable Plan",
        // Pricing EN (v3)
        "pricing.v3.title": "Subscription",
        "pricing.v3.subtitle": "Manage your plan and billing",
        "pricing.v3.compare": "Compare plans",
        "pricing.v3.save2months": "Save 2 months",
        "pricing.v3.monthly": "Monthly",
        "pricing.v3.yearly": "Yearly",
        "pricing.v3.trial.title": "Trial",
        "pricing.v3.trial.price": "0 DH",
        "pricing.v3.trial.btn": "Activate Trial",
        "pricing.v3.pro.title": "Pro",
        "pricing.v3.pro.price": "199 DH / month",
        "pricing.v3.pro.priceYearly": "1990 DH / year",
        "pricing.v3.pro.badge": "Recommended",
        "pricing.v3.pro.btn": "Choose Pro",
        "pricing.v3.prem.title": "Premium - Soon",
        "pricing.v3.prem.btn": "Soon",
        "pricing.v3.faq.title": "FAQ",
        "pricing.v3.secure": "Secure Payment",
        "pricing.v3.support": "Support",
        // Shared Features (v3)
        "pricing.feat.queue": "Queue Management",
        "pricing.feat.qr": "Patient QR Code",
        "pricing.feat.dashboard": "Doctor Dashboard",
        "pricing.feat.multi": "Multi-practitioners",
        "pricing.feat.sms": "Advanced SMS",
        "pricing.feat.stats": "Advanced Analytics",
        "pricing.feat.custom": "Full Customization",
        "pricing.v3.subtitle.badge": "Simple & Transparent",
        "pricing.feat.support24": "24/7 Support",
        // How It Works EN
        "how.title": "How does ClinicFlow work?",
        "how.subtitle": "A simple solution to organize patient queues in your clinic.",
        "how.btn.free": "Free Trial",
        "how.step1.title": "1. Doctor creates account",
        "how.step1.desc": "Sign up in minutes and configure your clinic details.",
        "how.step2.title": "2. Patients take a ticket",
        "how.step2.desc": "Patients take their turn directly at the clinic or via QR Code, no app needed.",
        "how.step3.title": "3. Doctor calls patient",
        "how.step3.desc": "From the dashboard, call the next patient with one click.",
        "how.step4.title": "4. Less waiting, more comfort",
        "how.step4.desc": "Patients are informed in real-time, waiting is reduced, and organization improved.",
        "how.why.title": "Why use ClinicFlow?",
        "how.why.1": "Reduced waiting time",
        "how.why.2": "Smooth clinic organization",
        "how.why.3": "Better patient experience",
        "how.why.4": "Simple and fast to use",
        "how.why.5": "Works on mobile and desktop",
        "how.target.title": "ClinicFlow is made for",
        "how.target.1": "Medical Offices",
        "how.target.2": "General Practitioners",
        "how.target.3": "Dentists",
        "how.target.4": "Private Clinics",
        "how.target.5": "Laboratories",
        "how.faq.title": "Frequently Asked Questions",
        "faq.q1": "Is the trial free?",
        "faq.a1": "Yes, you get a full 14-day free trial, no credit card required.",
        "faq.q2": "Do patients need an app?",
        "faq.a2": "No, no app needed. They just scan a QR Code or take a paper ticket.",
        "faq.q3": "Does ClinicFlow work without internet?",
        "faq.a3": "ClinicFlow is a cloud solution and requires internet to sync the queue.",
        "faq.q4": "Can I use it in a small clinic?",
        "faq.a4": "Absolutely. ClinicFlow fits all sizes, from solo doctors to large clinics.",
        "how.cta.title": "Simplify your clinic management today",
        "how.cta.btn": "Start for Free",
        // Contact EN
        "contact.title": "Contact",
        "contact.subtitle": "Need help or a demo? Contact us and we will reply quickly.",
        "contact.tab.demo": "Request a Demo",
        "contact.tab.msg": "Send a Message",
        "contact.form.name": "Full Name",
        "contact.form.email": "Email",
        "contact.form.phone": "Phone (optional)",
        "contact.form.type": "Request Type",
        "contact.form.type.support": "Support",
        "contact.form.type.sales": "Sales",
        "contact.form.type.other": "Other",
        "contact.form.msg": "Message",
        "contact.form.privacy": "I accept the privacy policy",
        "contact.form.send": "Send",
        "contact.info.support": "Support",
        "contact.info.whatsapp": "WhatsApp",
        "contact.info.address": "Address",
        "contact.info.reply": "Response within 24h",
        "contact.info.avail": "Available 9am-6pm",
        "contact.demo.title": "Doctor Demo",
        "contact.demo.desc": "We show you ClinicFlow in 10 minutes.",
        "contact.demo.clinic": "Clinic Name",
        "contact.demo.city": "City",
        "contact.demo.slot": "Preferred Slot",
        "contact.demo.book": "Book Now",
        "contact.cta.title": "Simplify your clinic management today",
        "contact.cta.btn": "Start Free Trial",
    },
    ar: {
        "queue.title": "قائمة الانتظار",
        "queue.empty": "لا يوجد مرضى في الانتظار",
        "current.title": "المريض الحالي",
        "current.none": "لا يوجد مريض حالياً",
        "current.start": "بدء القائمة",
        "current.helper": "سيتم استدعاء أول مريض",
        "action.next": "التالي",
        "action.finish": "إنهاء",
        "action.cancel": "إلغاء",
        "action.urgent": "عاجل",
        "action.delay": "تأجيل",
        "header.status.active": "القائمة نشطة",
        "header.status.stopped": "القائمة متوقفة",
        "settings.title": "الإعدادات",
        "settings.questions": "أسئلة المرضى",
        "logout": "تسجيل خروج",
        "nav.home": "الرئيسية",
        "nav.features": "المميزات",
        "nav.howItWorks": "كيف يعمل",
        "nav.pricing": "الأسعار",
        "nav.contact": "اتصل بنا",
        "nav.demo": "تجريبي للطبيب",
        "hero.headline": "أدر قائمة الانتظار.",
        "hero.subheadline": "ببساطة.",
        "hero.subtitle": "حسن تدفق المرضى، قلل وقت الانتظار وأرح موظفيك مع ClinicFlow.",
        "hero.cta": "ابدأ الآن",
        "hero.login": "دخول الطبيب",
        "cta.title": "جاهز لتحديث عيادتك؟",
        "cta.button": "ابدأ التجربة المجانية",
        "footer.rights": "جميع الحقوق محفوظة.",
        "footer.privacy": "سياسة الخصوصية",
        "admin.sidebar.clinics": "العيادات والاشتراكات",
        "admin.sidebar.support": "تذاكر الدعم",
        "admin.sidebar.overview": "نظرة عامة",
        "admin.clinics.title": "إدارة العيادات",
        "admin.clinics.subtitle": "إدارة العيادات والاشتراكات.",
        "admin.clinics.search": "البحث بالاسم، البريد الإلكتروني...",
        "admin.clinics.table.clinic": "اسم العيادة",
        "admin.clinics.table.subscription": "الاشتراك",
        "admin.clinics.table.patients": "المرضى",
        "admin.signout": "تسجيل خروج",
        // Settings AR
        "admin.settings.title": "الإعدادات العامة",
        "admin.settings.app": "إعدادات التطبيق واللغة",
        "admin.settings.app.name": "اسم التطبيق",
        "admin.settings.app.logo": "الشعار",
        "admin.settings.app.change": "تغيير",
        "admin.settings.app.lang": "اللفات",
        "admin.settings.app.lang.desc": "العربية، الإنجليزية، الفرنسية",
        "admin.settings.subs": "إعدادات الاشتراك الافتراضية",
        "admin.settings.subs.trial": "مدة الفترة التجريبية الافتراضية (أيام)",
        "admin.settings.subs.plan": "الخطة الافتراضية",
        "admin.settings.btn.save": "حفظ التغييرات",
        "admin.settings.btn.cancel": "إلغاء",
        // Admin AR
        "admin.sidebar.dashboard": "لوحة القيادة",
        "admin.sidebar.users": "المستخدمين",
        "admin.sidebar.subscriptions": "الاشتراكات",
        "admin.sidebar.plans": "الخطط",
        "admin.sidebar.periods": "الفترات",
        "admin.sidebar.features": "الخصائص",
        "admin.sidebar.settings": "الإعدادات",
        "admin.sidebar.logs": "السجلات",
        "admin.header.superadmin": "المدير العام",
        "admin.dashboard.title": "نظرة عامة",
        "admin.stats.users": "مجموع المستخدمين",
        "admin.stats.activeSubs": "اشتراكات نشطة",
        "admin.stats.revenue": "الدخل الشهري",
        "admin.stats.trials": "فترات تجريبية",
        "admin.users.title": "إدارة المستخدمين",
        "admin.users.filter.plan": "تصفية حسب الخطة",
        "admin.users.filter.status": "تصفية حسب الحالة",
        "admin.users.search": "بحث عن مستخدم",
        "admin.table.user": "المستخدم",
        "admin.table.plan": "الخطة",
        "admin.table.status": "الحالة",
        "admin.table.date": "التاريخ",
        "admin.table.actions": "إجراءات",
        // Features AR
        "admin.features.title": "إدارة تفعيل الخصائص",
        "admin.features.subtitle": "قم بتفعيل أو تعطيل الخصائص لكل خطة أو تجاوز الإعدادات لمستخدمين محددين.",
        "admin.features.table.name": "اسم الخاصية",
        "admin.features.table.desc": "الوصف",
        "admin.features.table.status": "الحالة العامة",
        "admin.features.table.plans": "مفعلة للخطط",
        "admin.features.table.override": "تجاوز لكل مستخدم",
        "admin.features.btn.manage": "إدارة التجاوزات",
        "admin.feature.qrcode": "QR Code",
        "admin.feature.qrcode.desc": "السماح للمرضى بمسح الكود لأخذ تذكرة",
        "admin.feature.appointments": "Appointments",
        "admin.feature.appointments.desc": "نظام حجز المواعيد عبر الإنترنت",
        "admin.feature.sms": "SMS Reminders",
        "admin.feature.sms.desc": "إرسال رسائل تذكير للمرضى",
        "admin.feature.multi": "Multi-practitioners",
        "admin.feature.multi.desc": "إدارة عدة أطباء في عيادة واحدة",
        "admin.feature.analytics": "Analytics",
        "admin.feature.analytics.desc": "تقارير مفصلة وإحصائيات",
        "admin.feature.branding": "Custom Branding",
        "admin.feature.branding.desc": "إزالة شعار ClinicFlow واستخدام شعار خاص",
        // Plans AR
        "admin.plans.title": "إدارة الخطط",
        "admin.plans.btn.create": "إنشاء خطة جديدة",
        "admin.plans.monthly": "السعر الشهري",
        "admin.plans.yearly": "السعر السنوي",
        "admin.plans.features": "المميزات",
        "admin.plans.limits": "الحدود",
        "admin.plans.limit.users": "المستخدمين",
        "admin.plans.limit.clinics": "العيادات",
        "admin.plans.limit.sms": "الرسائل",
        "admin.plans.btn.edit": "تعديل الخطة",
        "admin.plans.btn.disable": "تعطيل الخطة",
        // Pricing AR (v3)
        "pricing.v3.title": "الاشتراك",
        "pricing.v3.subtitle": "إدارة خطتك والفوترة",
        "pricing.v3.compare": "مقارنة الخطط",
        "pricing.v3.save2months": "وفر شهرين",
        "pricing.v3.monthly": "شهري",
        "pricing.v3.yearly": "سنوي",
        "pricing.v3.trial.title": "تجريبي",
        "pricing.v3.trial.price": "0 درهم",
        "pricing.v3.trial.btn": "تفعيل التجريبي",
        "pricing.v3.pro.title": "برو",
        "pricing.v3.pro.price": "199 درهم / شهر",
        "pricing.v3.pro.priceYearly": "1990 درهم / سنة",
        "pricing.v3.pro.badge": "موصى به",
        "pricing.v3.pro.btn": "اختر برو",
        "pricing.v3.prem.title": "بريميوم - قريباً",
        "pricing.v3.prem.btn": "قريباً",
        "pricing.v3.faq.title": "أسئلة شائعة",
        "pricing.v3.secure": "دفع آمن",
        "pricing.v3.support": "دعم فني",
        // Shared Features (v3)
        "pricing.feat.queue": "إدارة قائمة الانتظار",
        "pricing.feat.qr": "QR Code للمرضى",
        "pricing.feat.dashboard": "لوحة تحكم الطبيب",
        "pricing.feat.multi": "أطباء متعددون",
        "pricing.feat.sms": "رسائل نصية متقدمة",
        "pricing.feat.stats": "إحصائيات متقدمة",
        "pricing.feat.custom": "تخصيص كامل",
        "pricing.v3.subtitle.badge": "بسيط وشفاف",
        "pricing.feat.support24": "دعم 24/7",
        // How It Works AR
        "how.title": "كيف يعمل ClinicFlow؟",
        "how.subtitle": "حل بسيط لتنظيم طوابير الانتظار في عيادتك.",
        "how.btn.free": "تجربة مجانية",
        "how.step1.title": "1. الطبيب ينشئ حسابه",
        "how.step1.desc": "يسجل الطبيب في دقائق ويقوم بإعداد تفاصيل العيادة.",
        "how.step2.title": "2. المرضى يأخذون تذكرة",
        "how.step2.desc": "يأخذ المرضى دورهم مباشرة في العيادة أو عبر QR Code، بدون تطبيقات.",
        "how.step3.title": "3. الطبيب ينادي المريض",
        "how.step3.desc": "من لوحة التحكم، ينادي الطبيب المريض التالي بضغطة زر.",
        "how.step4.title": "4. انتظار أقل، راحة أكثر",
        "how.step4.desc": "يتم إبلاغ المرضى في الوقت الفعلي، مما يقلل الانتظار ويحسن التنظيم.",
        "how.why.title": "لماذا تستخدم ClinicFlow؟",
        "how.why.1": "تقليل وقت الانتظار",
        "how.why.2": "تنظيم سلس للعيادة",
        "how.why.3": "تجربة أفضل للمريض",
        "how.why.4": "بسيط وسريع الاستخدام",
        "how.why.5": "يعمل على الهاتف والكمبيوتر",
        "how.target.title": "ClinicFlow مصمم لـ",
        "how.target.1": "العيادات الطبية",
        "how.target.2": "الأطباء العامين",
        "how.target.3": "أطباء الأسنان",
        "how.target.4": "العيادات الخاصة",
        "how.target.5": "المختبرات",
        "how.faq.title": "أسئلة شائعة",
        "faq.q1": "هل التجربة مجانية؟",
        "faq.a1": "نعم، تحصل على 14 يومًا تجربة مجانية بالكامل، دون الحاجة لبطاقة ائتمان.",
        "faq.q2": "هل يحتاج المرضى لتطبيق؟",
        "faq.a2": "لا، لا حاجة لتطبيق. يقومون فقط بمسح QR Code أو أخذ تذكرة ورقية.",
        "faq.q3": "هل يعمل ClinicFlow بدون إنترنت؟",
        "faq.a3": "ClinicFlow هو حل سحابي ويتطلب إنترنت لمزامنة قائمة الانتظار.",
        "faq.q4": "هل يمكنني استخدامه في عيادة صغيرة؟",
        "faq.a4": "بالتأكيد. ClinicFlow يناسب جميع الأحجام، من الطبيب الفردي إلى العيادات الكبيرة.",
        "how.cta.title": "بسط إدارة عيادتك اليوم",
        "how.cta.btn": "ابدأ مجانًا",
        // Contact AR
        "contact.title": "اتصل بنا",
        "contact.subtitle": "تحتاج مساعدة أو عرض توضيحي؟ اتصل بنا وسنرد عليك بسرعة.",
        "contact.tab.demo": "طلب ديمو",
        "contact.tab.msg": "إرسال رسالة",
        "contact.form.name": "الاسم الكامل",
        "contact.form.email": "البريد الإلكتروني",
        "contact.form.phone": "الهاتف (اختياري)",
        "contact.form.type": "نوع الطلب",
        "contact.form.type.support": "دعم فني",
        "contact.form.type.sales": "مبيعات",
        "contact.form.type.other": "آخر",
        "contact.form.msg": "الرسالة",
        "contact.form.privacy": "أوافق على سياسة الخصوصية",
        "contact.form.send": "إرسال",
        "contact.info.support": "الدعم",
        "contact.info.whatsapp": "واتساب",
        "contact.info.address": "العنوان",
        "contact.info.reply": "الرد خلال 24 ساعة",
        "contact.info.avail": "متاح 9ص - 6م",
        "contact.demo.title": "ديمو للطبيب",
        "contact.demo.desc": "نعرض لك ClinicFlow في 10 دقائق.",
        "contact.demo.clinic": "اسم العيادة",
        "contact.demo.city": "المدينة",
        "contact.demo.slot": "الوقت المفضل",
        "contact.demo.book": "حجز الآن",
        "contact.cta.title": "بسط إدارة عيادتك اليوم",
        "contact.cta.btn": "ابدأ التجربة المجانية",
    },
};

type LanguageContextType = {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    dir: "ltr" | "rtl";
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>("fr");

    useEffect(() => {
        // Simple persistence
        const saved = localStorage.getItem("clinicflow_lang") as Language;
        if (saved && ["fr", "en", "ar"].includes(saved)) {
            setLanguage(saved);
        }
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem("clinicflow_lang", lang);
        document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
        document.documentElement.lang = lang;
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, dir: language === "ar" ? "rtl" : "ltr" }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
